//! TAS5830 Class-D amplifier driver
//!
//! Texas Instruments TAS5830 digital input Class-D amplifier
//! with integrated DSP. Controlled via I2C.
//!
//! ## DSP Firmware Loading
//!
//! The TAS5830 requires three binary files generated by TI's PPC3 tool:
//! - `*_dsp.bin` - DSP program code
//! - `*_coeff.bin` - Filter coefficients (biquads, gains, etc.)
//! - `*_ctrl.bin` - Control register settings
//!
//! These files are stored on the USB filesystem and loaded at boot.

use embedded_hal_async::i2c::I2c;

/// TAS5830 I2C address (configured by ADDR pin)
pub const DEFAULT_ADDRESS: u8 = 0x60;

/// TAS5830 register addresses (Page 0)
#[allow(dead_code)]
pub mod reg {
    // Page 0 registers
    pub const PAGE_SELECT: u8 = 0x00;
    pub const DEVICE_CTRL: u8 = 0x01;
    pub const DEV_MODE1: u8 = 0x02;
    pub const DEV_MODE2: u8 = 0x03;
    pub const RESET_CTRL: u8 = 0x04;
    pub const SIG_PATH: u8 = 0x0D;
    pub const FS_CTRL: u8 = 0x0E;
    pub const BCK_RATIO: u8 = 0x0F;
    pub const CLOCK_CFG: u8 = 0x10;
    pub const DSP_CFG: u8 = 0x11;
    pub const DIG_VOL: u8 = 0x4C;
    pub const DIG_VOL_CTRL: u8 = 0x4E;
    pub const AUTO_MUTE: u8 = 0x50;
    pub const ANA_CTRL: u8 = 0x53;
    pub const AGAIN: u8 = 0x54;
    pub const DSP_MISC: u8 = 0x66;
    pub const DIE_ID: u8 = 0x67;
    pub const POWER_STATE: u8 = 0x68;
    pub const FAULT: u8 = 0x70;
    pub const CHAN_FAULT: u8 = 0x71;
    pub const GLOBAL_FAULT1: u8 = 0x72;
    pub const GLOBAL_FAULT2: u8 = 0x73;
    pub const WARNING: u8 = 0x74;
    pub const PIN_STATUS: u8 = 0x75;
    pub const MISC_STATUS: u8 = 0x76;
    pub const CLEAR_FAULT: u8 = 0x78;
    pub const BOOK_SELECT: u8 = 0x7F;

    // Book 0 is control registers
    // Book 0x8C is DSP coefficient RAM
    // Book 0x64-0x67 is DSP program RAM
    pub const BOOK_CTRL: u8 = 0x00;
    pub const BOOK_COEFF: u8 = 0x8C;
    pub const BOOK_DSP_START: u8 = 0x64;
}

/// TAS5830 power state
#[derive(Debug, Clone, Copy, PartialEq, Eq, defmt::Format)]
pub enum PowerState {
    DeepSleep,
    Sleep,
    HiZ,
    Play,
    Unknown(u8),
}

impl From<u8> for PowerState {
    fn from(val: u8) -> Self {
        match val & 0x03 {
            0 => PowerState::DeepSleep,
            1 => PowerState::Sleep,
            2 => PowerState::HiZ,
            3 => PowerState::Play,
            _ => PowerState::Unknown(val),
        }
    }
}

/// TAS5830 driver error
#[derive(Debug, defmt::Format)]
pub enum Error<E> {
    /// I2C communication error
    I2c(E),
    /// Invalid firmware data
    InvalidFirmware,
    /// Device not responding or wrong ID
    DeviceNotFound,
    /// DSP not ready
    DspNotReady,
}

impl<E> From<E> for Error<E> {
    fn from(e: E) -> Self {
        Error::I2c(e)
    }
}

/// DSP firmware container
pub struct DspFirmware<'a> {
    /// DSP program binary
    pub dsp: &'a [u8],
    /// Coefficient binary
    pub coeff: &'a [u8],
    /// Control register binary
    pub ctrl: &'a [u8],
}

/// TAS5830 amplifier driver
pub struct Tas5830<I> {
    i2c: I,
    address: u8,
    volume: u8,
    muted: bool,
}

impl<I, E> Tas5830<I>
where
    I: I2c<Error = E>,
{
    /// Create a new TAS5830 driver
    pub fn new(i2c: I, address: u8) -> Self {
        Self {
            i2c,
            address,
            volume: 0x30, // Default -24dB
            muted: false,
        }
    }

    /// Create with default address (0x60)
    pub fn new_default(i2c: I) -> Self {
        Self::new(i2c, DEFAULT_ADDRESS)
    }

    /// Initialize the amplifier with basic settings (no DSP)
    ///
    /// Configures for 32-bit I2S input at 96kHz, stereo.
    /// Call `load_dsp_firmware()` after this for full DSP setup.
    pub async fn init(&mut self) -> Result<(), Error<E>> {
        // Read device ID to verify communication
        let die_id = self.read_reg(reg::DIE_ID).await?;
        defmt::info!("TAS5830 DIE_ID: {:#04x}", die_id);

        // Reset device
        self.write_reg(reg::RESET_CTRL, 0x01).await?;
        embassy_time::Timer::after(embassy_time::Duration::from_millis(5)).await;

        // Clear any existing faults
        self.write_reg(reg::CLEAR_FAULT, 0xFF).await?;

        // Configure device mode: I2S slave, 32-bit
        self.write_reg(reg::DEV_MODE1, 0x00).await?; // I2S slave mode
        self.write_reg(reg::DEV_MODE2, 0x02).await?; // 32-bit word length

        // Configure sample rate detection
        self.write_reg(reg::FS_CTRL, 0x00).await?; // Auto-detect

        // Signal path: stereo input, both channels active
        self.write_reg(reg::SIG_PATH, 0x00).await?;

        // Set initial volume
        self.write_reg(reg::DIG_VOL, self.volume).await?;
        self.write_reg(reg::DIG_VOL_CTRL, 0x00).await?; // Volume enabled

        // Configure analog gain (0dB)
        self.write_reg(reg::AGAIN, 0x00).await?;

        // Auto-mute disabled initially
        self.write_reg(reg::AUTO_MUTE, 0x00).await?;

        defmt::info!("TAS5830 basic init complete");
        Ok(())
    }

    /// Load DSP firmware from provided binary data
    ///
    /// This should be called after `init()` with firmware loaded from USB filesystem.
    pub async fn load_dsp_firmware(&mut self, fw: &DspFirmware<'_>) -> Result<(), Error<E>> {
        defmt::info!(
            "Loading DSP firmware: dsp={} bytes, coeff={} bytes, ctrl={} bytes",
            fw.dsp.len(),
            fw.coeff.len(),
            fw.ctrl.len()
        );

        // Put device in Hi-Z mode for programming
        self.write_reg(reg::DEVICE_CTRL, 0x02).await?;
        embassy_time::Timer::after(embassy_time::Duration::from_millis(5)).await;

        // Load DSP program RAM (Book 0x64-0x67)
        self.load_dsp_program(fw.dsp).await?;

        // Load coefficient RAM (Book 0x8C)
        self.load_coefficients(fw.coeff).await?;

        // Load control registers
        self.load_control_registers(fw.ctrl).await?;

        // Return to Book 0, Page 0
        self.select_book_page(0x00, 0x00).await?;

        // Exit Hi-Z mode - go to PLAY
        self.write_reg(reg::DEVICE_CTRL, 0x03).await?;
        embassy_time::Timer::after(embassy_time::Duration::from_millis(10)).await;

        // Verify we're in play mode
        let state = self.get_power_state().await?;
        if state != PowerState::Play {
            defmt::warn!("TAS5830 not in play mode after DSP load: {:?}", state);
        }

        defmt::info!("TAS5830 DSP firmware loaded successfully");
        Ok(())
    }

    /// Load DSP program RAM
    async fn load_dsp_program(&mut self, data: &[u8]) -> Result<(), Error<E>> {
        // DSP program spans Books 0x64-0x67
        // Each book has 256 pages, each page is 128 bytes
        let mut offset = 0usize;
        let mut book = 0x64u8;

        while offset < data.len() && book <= 0x67 {
            for page in 0u8..=255 {
                if offset >= data.len() {
                    break;
                }

                self.select_book_page(book, page).await?;

                // Write up to 128 bytes per page starting at register 0x00
                let chunk_size = core::cmp::min(128, data.len() - offset);
                let chunk = &data[offset..offset + chunk_size];

                // Write in 32-byte blocks (I2C buffer limitation)
                for (i, block) in chunk.chunks(32).enumerate() {
                    let reg_addr = (i * 32) as u8;
                    self.write_block(reg_addr, block).await?;
                }

                offset += chunk_size;
            }
            book += 1;
        }

        Ok(())
    }

    /// Load coefficient RAM
    async fn load_coefficients(&mut self, data: &[u8]) -> Result<(), Error<E>> {
        // Coefficients go to Book 0x8C
        let mut offset = 0usize;

        for page in 0u8..=255 {
            if offset >= data.len() {
                break;
            }

            self.select_book_page(reg::BOOK_COEFF, page).await?;

            let chunk_size = core::cmp::min(128, data.len() - offset);
            let chunk = &data[offset..offset + chunk_size];

            for (i, block) in chunk.chunks(32).enumerate() {
                let reg_addr = (i * 32) as u8;
                self.write_block(reg_addr, block).await?;
            }

            offset += chunk_size;
        }

        Ok(())
    }

    /// Load control register settings
    async fn load_control_registers(&mut self, data: &[u8]) -> Result<(), Error<E>> {
        // Control data is formatted as reg_addr, value pairs
        // Format from PPC3: [addr, value, addr, value, ...]
        if data.len() % 2 != 0 {
            return Err(Error::InvalidFirmware);
        }

        self.select_book_page(0x00, 0x00).await?;

        for chunk in data.chunks(2) {
            let reg = chunk[0];
            let val = chunk[1];

            // Skip certain registers that we control separately
            if reg == reg::DIG_VOL || reg == reg::DEVICE_CTRL {
                continue;
            }

            self.write_reg(reg, val).await?;
        }

        Ok(())
    }

    /// Select book and page
    async fn select_book_page(&mut self, book: u8, page: u8) -> Result<(), Error<E>> {
        // First go to page 0 to access book select
        self.i2c
            .write(self.address, &[reg::PAGE_SELECT, 0x00])
            .await?;
        // Select book
        self.i2c
            .write(self.address, &[reg::BOOK_SELECT, book])
            .await?;
        // Select page
        self.i2c
            .write(self.address, &[reg::PAGE_SELECT, page])
            .await?;
        Ok(())
    }

    /// Write a block of data starting at register address
    async fn write_block(&mut self, start_reg: u8, data: &[u8]) -> Result<(), Error<E>> {
        // Build buffer: [reg_addr, data...]
        let mut buf = [0u8; 33]; // Max 32 bytes + 1 for address
        buf[0] = start_reg;
        let len = core::cmp::min(data.len(), 32);
        buf[1..1 + len].copy_from_slice(&data[..len]);
        self.i2c.write(self.address, &buf[..1 + len]).await?;
        Ok(())
    }

    /// Set the digital volume
    ///
    /// Volume is in 0.5dB steps: 0x00 = 0dB, 0xFF = -127.5dB
    pub async fn set_volume(&mut self, volume: u8) -> Result<(), Error<E>> {
        self.volume = volume;
        if !self.muted {
            self.write_reg(reg::DIG_VOL, volume).await?;
        }
        defmt::debug!("TAS5830 volume: {:#04x} ({} dB)", volume, -(volume as i16) / 2);
        Ok(())
    }

    /// Get current volume setting
    pub fn get_volume(&self) -> u8 {
        self.volume
    }

    /// Set volume in percentage (0-100)
    pub async fn set_volume_percent(&mut self, percent: u8) -> Result<(), Error<E>> {
        // Map 0-100% to 0xCF-0x00 (mute to 0dB)
        let volume = if percent >= 100 {
            0x00
        } else {
            0xCF - ((percent as u16 * 0xCF) / 100) as u8
        };
        self.set_volume(volume).await
    }

    /// Get volume as percentage
    pub fn get_volume_percent(&self) -> u8 {
        if self.volume >= 0xCF {
            0
        } else {
            (((0xCF - self.volume) as u16 * 100) / 0xCF) as u8
        }
    }

    /// Mute the amplifier
    pub async fn mute(&mut self) -> Result<(), Error<E>> {
        self.muted = true;
        self.write_reg(reg::DIG_VOL, 0xFF).await?;
        defmt::debug!("TAS5830 muted");
        Ok(())
    }

    /// Unmute the amplifier
    pub async fn unmute(&mut self) -> Result<(), Error<E>> {
        self.muted = false;
        self.write_reg(reg::DIG_VOL, self.volume).await?;
        defmt::debug!("TAS5830 unmuted");
        Ok(())
    }

    /// Check if muted
    pub fn is_muted(&self) -> bool {
        self.muted
    }

    /// Toggle mute state
    pub async fn toggle_mute(&mut self) -> Result<bool, Error<E>> {
        if self.muted {
            self.unmute().await?;
        } else {
            self.mute().await?;
        }
        Ok(self.muted)
    }

    /// Read fault status
    pub async fn read_faults(&mut self) -> Result<u8, Error<E>> {
        self.read_reg(reg::FAULT).await
    }

    /// Clear fault status
    pub async fn clear_faults(&mut self) -> Result<(), Error<E>> {
        self.write_reg(reg::CLEAR_FAULT, 0xFF).await
    }

    /// Get power state
    pub async fn get_power_state(&mut self) -> Result<PowerState, Error<E>> {
        let state = self.read_reg(reg::POWER_STATE).await?;
        Ok(PowerState::from(state))
    }

    /// Write a single register
    async fn write_reg(&mut self, reg: u8, value: u8) -> Result<(), Error<E>> {
        self.i2c.write(self.address, &[reg, value]).await?;
        Ok(())
    }

    /// Read a single register
    async fn read_reg(&mut self, reg: u8) -> Result<u8, Error<E>> {
        let mut buf = [0u8; 1];
        self.i2c.write_read(self.address, &[reg], &mut buf).await?;
        Ok(buf[0])
    }

    /// Release the I2C bus
    pub fn release(self) -> I {
        self.i2c
    }
}
